// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RandomCards.Data;

#nullable disable

namespace RandomCards.Migrations
{
    [DbContext(typeof(CardDbContext))]
    partial class CardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RandomCards.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98e7cce4-94b6-4cd0-8df6-41dcb603e307"),
                            Name = "ace spades"
                        },
                        new
                        {
                            Id = new Guid("f5af3e55-f689-475d-bc2b-734cef2b7dbb"),
                            Name = "two spades"
                        },
                        new
                        {
                            Id = new Guid("dc4bb902-9a00-443a-8631-11a0d01d5d87"),
                            Name = "three spades"
                        },
                        new
                        {
                            Id = new Guid("6e65fb09-8724-4e56-a872-661a67b618ed"),
                            Name = "four spades"
                        },
                        new
                        {
                            Id = new Guid("62c54a96-a720-450c-a2eb-572c02fd3e70"),
                            Name = "five spades"
                        },
                        new
                        {
                            Id = new Guid("cf682d09-92bb-4709-9106-0b640595f1a2"),
                            Name = "six spades"
                        },
                        new
                        {
                            Id = new Guid("983e67da-26a5-414e-8fe2-a421affb711c"),
                            Name = "seven spades"
                        },
                        new
                        {
                            Id = new Guid("4408917d-a2d1-44e0-b4f6-2a02e0d50f60"),
                            Name = "eight spades"
                        },
                        new
                        {
                            Id = new Guid("ad34c0c4-f4a5-42d6-a99e-6cf24702b15a"),
                            Name = "nine spades"
                        },
                        new
                        {
                            Id = new Guid("6b19b8ca-a9df-4922-bc62-45caf8abd751"),
                            Name = "ten spades"
                        },
                        new
                        {
                            Id = new Guid("ec2a8f90-6bb1-4400-8b86-f4171eb7a59f"),
                            Name = "jack spades"
                        },
                        new
                        {
                            Id = new Guid("f920a120-e313-408d-8a29-cc28a8ab33d3"),
                            Name = "queen spades"
                        },
                        new
                        {
                            Id = new Guid("c9e39fc0-99f0-49d0-ae1d-ade982eb5f01"),
                            Name = "king spades"
                        },
                        new
                        {
                            Id = new Guid("8bc8ba28-46b6-4be5-b03a-d30bc518e8ab"),
                            Name = "ace diamonds"
                        },
                        new
                        {
                            Id = new Guid("32e104a6-befc-4432-81a0-70e84ff298f8"),
                            Name = "two diamonds"
                        },
                        new
                        {
                            Id = new Guid("73db7e58-d6b5-45a9-bce9-015bcda10c77"),
                            Name = "three diamonds"
                        },
                        new
                        {
                            Id = new Guid("c6824e2e-1e5a-468c-bc36-7f66168d526a"),
                            Name = "four diamonds"
                        },
                        new
                        {
                            Id = new Guid("19731224-4d0d-418c-87eb-152815c5ceb7"),
                            Name = "five diamonds"
                        },
                        new
                        {
                            Id = new Guid("f736ceaf-9c5f-4bbe-aaa0-cdd57e1af9b9"),
                            Name = "six diamonds"
                        },
                        new
                        {
                            Id = new Guid("7365766e-9647-46dd-b8c6-da9a035574fa"),
                            Name = "seven diamonds"
                        },
                        new
                        {
                            Id = new Guid("ee8bf6b8-23cd-44c8-8a6d-b1323e8c249d"),
                            Name = "eight diamonds"
                        },
                        new
                        {
                            Id = new Guid("a1f34cd1-4886-4bab-a841-2bf0d42eae67"),
                            Name = "nine diamonds"
                        },
                        new
                        {
                            Id = new Guid("9d3948e4-7de3-4b9b-a5a9-5430bd6dc380"),
                            Name = "ten diamonds"
                        },
                        new
                        {
                            Id = new Guid("71590413-64da-435b-a1c2-5900be671423"),
                            Name = "jack diamonds"
                        },
                        new
                        {
                            Id = new Guid("f7d937ea-18fa-45bb-a1be-fd41833404d2"),
                            Name = "queen diamonds"
                        },
                        new
                        {
                            Id = new Guid("e5924894-1581-4800-ac0d-76d71019fa64"),
                            Name = "king diamonds"
                        },
                        new
                        {
                            Id = new Guid("1e982343-74b0-49c7-a32d-76ca4aa031d6"),
                            Name = "ace clubs"
                        },
                        new
                        {
                            Id = new Guid("b2826b86-3a89-42db-b4d0-9537df2856af"),
                            Name = "two clubs"
                        },
                        new
                        {
                            Id = new Guid("271d9f70-6cdb-4774-a77a-4d5d23c181af"),
                            Name = "three clubs"
                        },
                        new
                        {
                            Id = new Guid("37e117ad-ad6a-4efc-b169-33b4d64a1538"),
                            Name = "four clubs"
                        },
                        new
                        {
                            Id = new Guid("c0e3ccfb-a42f-46c3-af33-2e4ba5a4b75b"),
                            Name = "five clubs"
                        },
                        new
                        {
                            Id = new Guid("4ca2dcb8-26df-44c8-9876-255117009282"),
                            Name = "six clubs"
                        },
                        new
                        {
                            Id = new Guid("0469eb70-5b2a-4c6b-b32c-56e96b8a29f9"),
                            Name = "seven clubs"
                        },
                        new
                        {
                            Id = new Guid("8728bd70-e221-4f07-a4c8-ee0cc27b5db8"),
                            Name = "eight clubs"
                        },
                        new
                        {
                            Id = new Guid("6be41e35-9e98-4885-9c66-c5bdb7ac4c7c"),
                            Name = "nine clubs"
                        },
                        new
                        {
                            Id = new Guid("2389b1b1-60e8-4b07-a6f1-f6f2f82adb4f"),
                            Name = "ten clubs"
                        },
                        new
                        {
                            Id = new Guid("1fbf3919-8759-4f48-9bb0-3d24c2b158e3"),
                            Name = "jack clubs"
                        },
                        new
                        {
                            Id = new Guid("1edb0043-55d4-4968-84c6-2c33d7cb4460"),
                            Name = "queen clubs"
                        },
                        new
                        {
                            Id = new Guid("7fe4b0f1-47c6-453e-b505-f8b34eb34e72"),
                            Name = "king clubs"
                        },
                        new
                        {
                            Id = new Guid("acaa772f-ce0b-4e87-920c-559658f5f55e"),
                            Name = "ace hearts"
                        },
                        new
                        {
                            Id = new Guid("c4463788-e536-4ab3-9f3d-41634794b23a"),
                            Name = "two hearts"
                        },
                        new
                        {
                            Id = new Guid("89c9e14e-43e0-4370-8ab6-399e3349e54f"),
                            Name = "three hearts"
                        },
                        new
                        {
                            Id = new Guid("c5980d42-e872-4c3f-897b-12960e757ee9"),
                            Name = "four hearts"
                        },
                        new
                        {
                            Id = new Guid("1cf39836-be86-45f9-8ee1-8e1d8937cdde"),
                            Name = "five hearts"
                        },
                        new
                        {
                            Id = new Guid("6f0b28e9-27cb-4429-b163-81ceea403c4b"),
                            Name = "six hearts"
                        },
                        new
                        {
                            Id = new Guid("6f5a54d4-e078-46ed-837b-0f607ad453d9"),
                            Name = "seven hearts"
                        },
                        new
                        {
                            Id = new Guid("e8d2839b-cc4d-46ca-8720-211ea4f5d44d"),
                            Name = "eight hearts"
                        },
                        new
                        {
                            Id = new Guid("cd68faa7-5051-4383-8826-c32eda7b7e2c"),
                            Name = "nine hearts"
                        },
                        new
                        {
                            Id = new Guid("995a67f9-cbde-4d58-b3c9-83d6e4f98663"),
                            Name = "ten hearts"
                        },
                        new
                        {
                            Id = new Guid("19349b74-e865-487c-9c20-a4d7f863626e"),
                            Name = "jack hearts"
                        },
                        new
                        {
                            Id = new Guid("8a4e0aca-11a9-47db-b237-e459b727ba9a"),
                            Name = "queen hearts"
                        },
                        new
                        {
                            Id = new Guid("9f5eedef-e175-45cb-bf5b-1bb8a381d029"),
                            Name = "king hearts"
                        });
                });

            modelBuilder.Entity("RandomCards.Models.CardGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("GameId");

                    b.ToTable("Cards_Games");
                });

            modelBuilder.Entity("RandomCards.Models.CardHand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("HandId");

                    b.ToTable("Cards_Hands");
                });

            modelBuilder.Entity("RandomCards.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RandomCards.Models.Hand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Hands");
                });

            modelBuilder.Entity("RandomCards.Models.CardGame", b =>
                {
                    b.HasOne("RandomCards.Models.Card", "Card")
                        .WithMany("CardGames")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RandomCards.Models.Game", "Game")
                        .WithMany("CardGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("RandomCards.Models.CardHand", b =>
                {
                    b.HasOne("RandomCards.Models.Card", "Card")
                        .WithMany("CardHands")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RandomCards.Models.Hand", "Hand")
                        .WithMany("CardHands")
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Hand");
                });

            modelBuilder.Entity("RandomCards.Models.Hand", b =>
                {
                    b.HasOne("RandomCards.Models.Game", "Game")
                        .WithMany("Hands")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("RandomCards.Models.Card", b =>
                {
                    b.Navigation("CardGames");

                    b.Navigation("CardHands");
                });

            modelBuilder.Entity("RandomCards.Models.Game", b =>
                {
                    b.Navigation("CardGames");

                    b.Navigation("Hands");
                });

            modelBuilder.Entity("RandomCards.Models.Hand", b =>
                {
                    b.Navigation("CardHands");
                });
#pragma warning restore 612, 618
        }
    }
}
