// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RandomCards.Data;

#nullable disable

namespace RandomCards.Migrations
{
    [DbContext(typeof(CardDbContext))]
    partial class CardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RandomCards.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("238e4681-01fc-401b-8aa1-22a0ba33c0ed"),
                            Name = "ace spades"
                        },
                        new
                        {
                            Id = new Guid("aef6f91c-c971-4b95-b78c-1f332315b450"),
                            Name = "two spades"
                        },
                        new
                        {
                            Id = new Guid("80440e50-c45a-4a41-abf8-af463fa81e7e"),
                            Name = "three spades"
                        },
                        new
                        {
                            Id = new Guid("bfea8731-5e20-4f31-8924-28cbcff67f09"),
                            Name = "four spades"
                        },
                        new
                        {
                            Id = new Guid("dae89307-40fc-4aee-beb3-da3abf844f24"),
                            Name = "five spades"
                        },
                        new
                        {
                            Id = new Guid("8a73578a-446a-4aab-9b52-fee34ffc3719"),
                            Name = "six spades"
                        },
                        new
                        {
                            Id = new Guid("b532c608-e6d4-466e-8be3-027c0fb2e7d7"),
                            Name = "seven spades"
                        },
                        new
                        {
                            Id = new Guid("90560d2a-7801-44c4-96db-216e355dfaec"),
                            Name = "eight spades"
                        },
                        new
                        {
                            Id = new Guid("c01a3f29-04fe-4c62-8b7e-9331bafc304f"),
                            Name = "nine spades"
                        },
                        new
                        {
                            Id = new Guid("1affa909-0d49-4416-bd36-1755174b4d44"),
                            Name = "ten spades"
                        },
                        new
                        {
                            Id = new Guid("8f18fd94-6b52-4153-b428-3954e67d13b7"),
                            Name = "jack spades"
                        },
                        new
                        {
                            Id = new Guid("8737dfb1-90cd-4012-8bbb-e778380f4d97"),
                            Name = "queen spades"
                        },
                        new
                        {
                            Id = new Guid("afe3f754-66cb-4f3e-b547-404d10f1b348"),
                            Name = "king spades"
                        },
                        new
                        {
                            Id = new Guid("c08abff6-e64a-47aa-8c2d-fa6e8284a0f9"),
                            Name = "ace diamonds"
                        },
                        new
                        {
                            Id = new Guid("993e4ccd-d2a9-4885-b9dc-c67e4a5e44c7"),
                            Name = "two diamonds"
                        },
                        new
                        {
                            Id = new Guid("498705b5-91f2-42c0-9671-cb94d52166a8"),
                            Name = "three diamonds"
                        },
                        new
                        {
                            Id = new Guid("958bdeea-5f12-4525-a052-de461995188e"),
                            Name = "four diamonds"
                        },
                        new
                        {
                            Id = new Guid("fc62d3f2-09a4-4361-9ac6-50aa5379533f"),
                            Name = "five diamonds"
                        },
                        new
                        {
                            Id = new Guid("5b69ac5c-c90c-4c45-9916-754614639262"),
                            Name = "six diamonds"
                        },
                        new
                        {
                            Id = new Guid("8ed83420-09cb-461f-b5b4-08743abb945b"),
                            Name = "seven diamonds"
                        },
                        new
                        {
                            Id = new Guid("52e8e7de-7324-4f74-9fb4-bc948835ea8d"),
                            Name = "eight diamonds"
                        },
                        new
                        {
                            Id = new Guid("e4d504be-95ff-40cc-9429-9f04ad1d1906"),
                            Name = "nine diamonds"
                        },
                        new
                        {
                            Id = new Guid("002e8179-dae8-48e0-90d0-98616ac415ad"),
                            Name = "ten diamonds"
                        },
                        new
                        {
                            Id = new Guid("74ca0cd9-c72a-43d8-8747-ed0d22cdce42"),
                            Name = "jack diamonds"
                        },
                        new
                        {
                            Id = new Guid("7ac11b15-ae16-476c-aa7d-a65c944b7575"),
                            Name = "queen diamonds"
                        },
                        new
                        {
                            Id = new Guid("7c418ace-366f-477d-bc2f-d570f7c5f9b2"),
                            Name = "king diamonds"
                        },
                        new
                        {
                            Id = new Guid("d936ec3a-6e43-4558-88d9-775d934667c7"),
                            Name = "ace clubs"
                        },
                        new
                        {
                            Id = new Guid("236ba3d4-2d1d-4a9d-a4d5-01f94b6364bd"),
                            Name = "two clubs"
                        },
                        new
                        {
                            Id = new Guid("1dcbcf94-11a0-45b8-b8fa-301303bb8597"),
                            Name = "three clubs"
                        },
                        new
                        {
                            Id = new Guid("f1883297-e207-4818-a2ed-70b6ea208323"),
                            Name = "four clubs"
                        },
                        new
                        {
                            Id = new Guid("d0b27ce1-5b43-4a2a-b2fb-7288824a4d85"),
                            Name = "five clubs"
                        },
                        new
                        {
                            Id = new Guid("e5445d3d-5152-4163-a18b-16f6576e3ecd"),
                            Name = "six clubs"
                        },
                        new
                        {
                            Id = new Guid("38c94d1c-77a4-4905-a6be-3cbab449dc8e"),
                            Name = "seven clubs"
                        },
                        new
                        {
                            Id = new Guid("0c9eafe8-796c-47f8-a2c4-98b1ed6b8594"),
                            Name = "eight clubs"
                        },
                        new
                        {
                            Id = new Guid("53166a74-02a2-453d-9008-e663878646c1"),
                            Name = "nine clubs"
                        },
                        new
                        {
                            Id = new Guid("668a3a70-3017-486c-9f69-81f9bd63f4a0"),
                            Name = "ten clubs"
                        },
                        new
                        {
                            Id = new Guid("1f5873d4-d3cf-45c5-8eb0-9c5522bcce7b"),
                            Name = "jack clubs"
                        },
                        new
                        {
                            Id = new Guid("c856f539-4e1e-42e4-b6e2-dd88b0df8f04"),
                            Name = "queen clubs"
                        },
                        new
                        {
                            Id = new Guid("131531af-4780-4353-89f9-4bd912acaea2"),
                            Name = "king clubs"
                        },
                        new
                        {
                            Id = new Guid("aa29854a-1e9f-4174-854e-dd9aa9be1265"),
                            Name = "ace hearts"
                        },
                        new
                        {
                            Id = new Guid("80fd5156-2b21-44ee-826a-24d40e06d0ca"),
                            Name = "two hearts"
                        },
                        new
                        {
                            Id = new Guid("300753dc-b007-4db4-9f70-33c152dbf0f2"),
                            Name = "three hearts"
                        },
                        new
                        {
                            Id = new Guid("73f0cea1-0cb0-4983-85ac-60b89b3d47ed"),
                            Name = "four hearts"
                        },
                        new
                        {
                            Id = new Guid("5379d24a-26cb-4ea7-bdb6-cf5c6a894247"),
                            Name = "five hearts"
                        },
                        new
                        {
                            Id = new Guid("7ba88865-7260-465f-9ce5-cb6ee99c9935"),
                            Name = "six hearts"
                        },
                        new
                        {
                            Id = new Guid("3696a4f0-f341-40fa-834b-392f32ac7ca0"),
                            Name = "seven hearts"
                        },
                        new
                        {
                            Id = new Guid("3aeea3db-ca81-4e8b-9861-960801e96c9c"),
                            Name = "eight hearts"
                        },
                        new
                        {
                            Id = new Guid("28c51d75-82f4-4074-9895-21e38f4893dd"),
                            Name = "nine hearts"
                        },
                        new
                        {
                            Id = new Guid("be2f34a5-19a2-40e3-a3d8-4a33e5358b9b"),
                            Name = "ten hearts"
                        },
                        new
                        {
                            Id = new Guid("cc134b31-7b79-4e43-89e8-bdce747bbbed"),
                            Name = "jack hearts"
                        },
                        new
                        {
                            Id = new Guid("3b5c34e5-b065-43f2-9443-a08785796121"),
                            Name = "queen hearts"
                        },
                        new
                        {
                            Id = new Guid("17260e2c-29e1-40d5-8644-9fb90550c846"),
                            Name = "king hearts"
                        });
                });

            modelBuilder.Entity("RandomCards.Models.CardGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("GameId");

                    b.ToTable("Cards_Games");
                });

            modelBuilder.Entity("RandomCards.Models.CardHand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("HandId");

                    b.ToTable("Cards_Hands");
                });

            modelBuilder.Entity("RandomCards.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeStamp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RandomCards.Models.Hand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeStamp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Hands");
                });

            modelBuilder.Entity("RandomCards.Models.CardGame", b =>
                {
                    b.HasOne("RandomCards.Models.Card", "Card")
                        .WithMany("CardGames")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RandomCards.Models.Game", "Game")
                        .WithMany("CardGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("RandomCards.Models.CardHand", b =>
                {
                    b.HasOne("RandomCards.Models.Card", "Card")
                        .WithMany("CardHands")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RandomCards.Models.Hand", "Hand")
                        .WithMany("CardHands")
                        .HasForeignKey("HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Hand");
                });

            modelBuilder.Entity("RandomCards.Models.Hand", b =>
                {
                    b.HasOne("RandomCards.Models.Game", "Game")
                        .WithMany("Hands")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("RandomCards.Models.Card", b =>
                {
                    b.Navigation("CardGames");

                    b.Navigation("CardHands");
                });

            modelBuilder.Entity("RandomCards.Models.Game", b =>
                {
                    b.Navigation("CardGames");

                    b.Navigation("Hands");
                });

            modelBuilder.Entity("RandomCards.Models.Hand", b =>
                {
                    b.Navigation("CardHands");
                });
#pragma warning restore 612, 618
        }
    }
}
